on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install

      - name: Deploy Github pages
        run: |
          git config user.name "Phát Mai"
          git config user.email "tienphat1501@gmail.com"
          yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
